name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: 'Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure gcloud CLI
        uses: google-github-actions/deploy-appengine@v1
        with:
          env_vars: |-
            MONGODB_URI=${{ secrets.MONGODB_URI }}
          
      - name: Install dependencies
        run: npm install

      - name: Build the Nest.js app
        run: npm run build

      - name: Deploy to App Engine
        run: gcloud app deploy
